#!/usr/bin/env python3
# ============================================================================
# make_gpu_table.py -- phone-GPU results table, f16 KV.  (2026-08-05)
#
# f16 EVERYWHERE, and that is not a preference. Quantized KV is numerically broken
# on this Adreno/Vulkan build: with q8_0 the model emits random tokens and
# teacher-forced NLL exceeds ln(vocab). The first pass of this table ran vanilla
# and muKV at q8_0 (corrupt) while SnapKV's preset forced f16 (valid), so every
# ratio divided a good run by a bad one. f16 is both correct and the only format
# every policy can share -- a per-head evictor needs FA-off, and llama.cpp requires
# flash-attention for a quantized V.
#
# MEDIAN, NOT MEAN, over repeats, with the full range shown. Run 1 of the
# Llama-1B vanilla and muKV arms is 18-33% faster than runs 2-3 while the
# no-compaction arm is tight to 1% -- a thermal-state artifact of the first cell
# after a long cool-down. Dropping run 1 would be cherry-picking; a mean lets it
# drag the estimate. The median is robust and the range makes the spread visible.
#
# Retention is in CELLS, which is invariant to cache format, so it stays comparable
# with the LongBench and NIAH tables.
# ============================================================================
import json, re, os, sys, statistics as st

BASE = sys.argv[1] if len(sys.argv) > 1 else "/tmp/phone_gpu_16k"
BASE8 = "/tmp/phone_gpu_8k"   # Phi-3 compaction only fits at ctx 8192 (see below)
GEOM = {"llama1b": (16, 8, 64), "phi3": (32, 32, 96)}
MODELS = [("llama1b", "Llama-3.2-1B"), ("phi3", "Phi-3-mini")]
POL = [("vanilla", "vanilla (full cache)"), ("mukv_dfg", r"$\mu$KV + round-trip"),
       ("mukv_ip", r"\textbf{$\mu$KV + in-place}"),
       ("mukv_nodfg", r"$\mu$KV, no compaction"), ("snapkv", "SnapKV"),
       ("adakv", "Ada-KV"), ("tova", "TOVA"), ("h2o", "H2O"),
       ("streamingllm", "StreamingLLM")]


def load(p):
    s = open(p).read()
    s = re.sub(r':\s*-?nan\b', ': NaN', s); s = re.sub(r':\s*-?inf\b', ': Infinity', s)
    return json.loads(s)


def fmt_of(d):
    e = os.path.join(d, "err")
    if not os.path.exists(e):
        return None
    for l in open(e, errors="replace"):
        if "KV cache types" in l:
            m = re.search(r'K=(\S+) V=(\S+)', l)
            return m.group(1) + "/" + m.group(2)
    return None


def runs(mt, suf):
    out = []
    for tag in [suf, suf + "_r2", suf + "_r3"]:
        d = os.path.join(BASE, "%s_%s" % (mt, tag))
        f = os.path.join(d, "meta.json")
        if not os.path.exists(f) or fmt_of(d) != "f16/f16":
            continue
        j = load(f)
        if (j.get("n_decode_steps") or 0) > 1000:     # timed cells generate 4096
            out.append(j)
    return out


print("% auto-generated by scripts/make_gpu_table.py -- do not hand-edit")
print(r"\begin{table}[tb]")
print(r"\caption{Mobile GPU (Adreno 840): 12K-token WikiText prompt $+$ 4096 generated "
      r"$=$ the full 16384 context, batch 1, cold-start gate (DDR $\le35$\,\textdegree C, "
      r"battery $\le33$\,\textdegree C) before every cell. \textbf{f16 K/V for every policy}: "
      r"quantized KV is numerically broken on this Adreno build (the model emits random tokens; "
      r"teacher-forced NLL exceeds $\ln(\text{vocab})$), and f16 is in any case the only format "
      r"all policies can share, since a per-head evictor needs FA-off and llama.cpp requires "
      r"flash-attention for a quantized V. Values are the median of $n$ runs with the range in "
      r"brackets. \textbf{Cells} is retained cache in KV cells, invariant to cache format. "
      r"Phi-3 $\mu$KV is reported at ctx 8192: compaction restores into a \emph{second} context, "
      r"so its peak demand is twice the cache, and at 16K in f16 that is $2\times6.44+2.4=15.28$\,GB "
      r"against 15.1\,GB of phone RAM --- every 16K Phi-3 cell records compaction\ub applied=False. "
      r"Llama-1B needs only 1.87\,GB and compacts at 16K. This is the same 2$\times$ round-trip bound "
      r"that limits compaction at 64K on the RTX.}")
print(r"\label{tab:gpu-wikitext}")
print(r"\centering\small")
print(r"\setlength{\tabcolsep}{4pt}")
print(r"\begin{tabular}{l l r r r r r}")
print(r"\toprule")
print(r"\textbf{Model} & \textbf{Policy} & \textbf{$n$} & \textbf{Prefill} & "
      r"\textbf{tok/s} & \textbf{dec\,$\times$} & \textbf{Cells} \\")
print(r"\midrule")
missing = []
for mt, disp in MODELS:
    v = runs(mt, "vanilla")
    if not v:
        continue
    vd = st.median([x["decode_ms"] for x in v])
    print(r"\multicolumn{7}{l}{\emph{%s}} \\" % disp)
    L_, H, D = GEOM[mt]
    for suf, lab in POL:
        g = runs(mt, suf)
        if not g:
            missing.append("%s/%s" % (mt, suf))
            # Phi-3 muKV at 16K is not "pending" -- it is INFEASIBLE on this device and
            # we have measured why (compaction's 2x peak exceeds phone RAM). Saying
            # "pending" would imply a number is still coming. The 8K block below is the
            # measurement; this row states the bound.
            note = (r"\emph{does not fit at 16K --- see ctx 8192 below}"
                    if (mt, suf) == ("phi3", "mukv_dfg") else r"\emph{not measured}")
            print(r"  & %-24s & \multicolumn{4}{c}{%s} & --- \\" % (lab, note))
            continue
        tps = [x.get("decode_tps") or 0 for x in g]
        rng = (" [%.1f--%.1f]" % (min(tps), max(tps))) if len(g) > 1 else ""
        print("  & %-24s & %d & %.0f & %.2f%s & %.2f$\\times$ & %.0f \\\\" % (
            lab, len(g), st.median([x["prefill_ms"] for x in g]) / 1000,
            st.median(tps), rng, vd / st.median([x["decode_ms"] for x in g]),
            g[0]["retained_kv_bytes"] / (L_ * H * D * 2 * 2.0)))
    print(r"\midrule")
# Phi-3 muKV+compaction CANNOT be measured at 16K on this phone: compaction needs a
# SECOND context, so peak demand is 2 x 6.44 GB of f16 KV + 2.4 GB of weights =
# 15.28 GB against 15.1 GB of RAM. Every f16 Phi-3 cell at 16K records
# compaction_applied=False for that reason. At 8K the peak is 8.84 GB and it fits.
# Reported as its own block so the context is never confused with the 16K rows.
import os as _os
if _os.path.isdir(BASE8):
    def r8(pol):
        g=[]
        for r in ["","_r2","_r3"]:
            f=_os.path.join(BASE8,"phi3_8k_%s%s"%(pol,r),"meta.json")
            if _os.path.exists(f): g.append(load(f))
        return g
    v8=r8("vanilla"); m8=r8("mukv_dfg")
    if v8 and m8:
        print(r"\midrule")
        print(r"\multicolumn{7}{l}{\emph{Phi-3-mini, ctx 8192 --- the largest context where compaction fits (see caption)}} \\")
        vd8=st.median([x["decode_ms"] for x in v8])
        for g,lab in ((v8,"vanilla (full cache)"),(m8,r"\textbf{$\mu$KV}")):
            tps=[x.get("decode_tps") or 0 for x in g]
            print("  & %-24s & %d & %.0f & %.2f [%.1f--%.1f] & %.2f$\\times$ & %.0f \\\\"%(
                lab,len(g),st.median([x["prefill_ms"] for x in g])/1000,st.median(tps),
                min(tps),max(tps),vd8/st.median([x["decode_ms"] for x in g]),
                g[0]["retained_kv_bytes"]/(32*32*96*2*2.0)))
print(r"\bottomrule")
print(r"\end{tabular}")
print(r"\end{table}")
if missing:
    sys.stderr.write("MISSING CELLS: %s\n" % ", ".join(missing))
